version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ServiceNow"
s3_bucket = "awsdevopsguruservicenow"
s3_prefix = "ServiceNow"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
