version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverlessrepo-DevOps-Guru-ServiceNow-Connector"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-96y429pwgq4l"
s3_prefix = "serverlessrepo-DevOps-Guru-ServiceNow-Connector"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
parameter_overrides = "ServiceNowHost=\"dev98071.service-now.com\" SecretName=\"servicenow_creds\""
