AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ServiceNowFunctions

  SAM Template for ServiceNowFunctions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  UserName:
    Type: String
  Password:
    Type: String
  ServiceNowHost:
    Type: String
Metadata:
  AWS::ServerlessRepo::Application:
    Name: servicenow
    Description: ServiceNow Integration
    Author: AWS
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ./LICENSE.txt
    ReadmeUrl: ./README.md
    Labels: [ 'ServiceNow', 'AWS', 'DevOpsGuru' ]
    HomePageUrl: https://github.com/aws-samples/amazon-devops-guru-connector-servicenow
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/aws-samples/amazon-devops-guru-connector-servicenow

Resources:
  Functions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Functions
      Handler: aws.devopsguru.partner.servicenow.InsightHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          USER_NAME: !Ref UserName
          PASSWORD: !Ref Password
          SERVICE_NOW_HOST: !Ref ServiceNowHost
      Policies: 
        - AmazonDevOpsGuruReadOnlyAccess
      Events:
        DevOpsGuru:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
