AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ServiceNowFunctions

  SAM Template for ServiceNowFunctions

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters:
  ServiceNowHost:
    Type: String
  SecretName:
    Type: String
Metadata:
  AWS::ServerlessRepo::Application:
    Name: DevOps-Guru-ServiceNow-Connector
    Description: Creates an Lambda function template for integrating ServiceNow with DevOpsGuru
    Author: Amazon DevOps Guru
    SpdxLicenseId: Apache-2.0
    LicenseUrl: ./LICENSE.txt
    ReadmeUrl: ./README.md
    Labels: [ 'ServiceNow' , 'DevOps-Guru']
    HomePageUrl: https://aws.amazon.com/devops-guru/
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/aws-samples/amazon-devops-guru-connector-servicenow

Resources:
  Functions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Functions
      Handler: aws.devopsguru.partner.servicenow.InsightHandler::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SERVICE_NOW_HOST: !Ref ServiceNowHost
          SECRET_NAME: !Ref SecretName
      Policies:
        - AmazonDevOpsGuruReadOnlyAccess
      Events:
        DevOpsGuru:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source:
                - "aws.devops-guru"
